namespace: extreme
name: voss
version: 0.1.0
readme: README.md
authors:
    - Ujwal Komarla
description: An Ansible collection for managing Extreme Networks devices running VOSS.
license: GPL-3.0-or-later
license_file: COPYING
dependencies:
  "ansible.netcommon": "*"
repository: git@github.com:extremenetworks/ansible_collections.extreme.voss.git
documentation: https://github.com/extremenetworks/ansible_collections.extreme.voss/tree/master/docs
homepage: https://github.com/extremenetworks/ansible_collections.extreme.voss
issues: https://github.com/extremenetworks/ansible_collections.extreme.voss/issues
tags:
    - networking
    - voss
    - extreme
    - switching
    - collection
